service: merkle-funder-task
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  environment: ${file(env-vars.js)}

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: true

package:
  patterns:
    - ./deployments/references.json
    - ./config/config.json

functions:
  fundHandler:
    handler: src/handler.run
    timeout: 60
    events:
      - schedule: rate(1 minute)
