service: merkle-funder-task
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: true

package:
  patterns:
    - ./deployments/**
    - '!./deployments/**/solcInputs'
    - ./deployments/**/.chainId
    - ./config/config.json
    - ./config/credentials.json

functions:
  fundHandler:
    handler: src/handler.run
    events:
      - schedule: rate(1 minute)
